import type { RunTrip } from './types';

const img = (seed: string, w = 1200, h = 800) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const RUNTRIPS: RunTrip[] = [
  {
    id: 'rt-tokyo',
    slug: 'tokyo-marathon-2027',
    destination: '도쿄',
    country: '일본',
    raceName: '2027 도쿄 마라톤',
    startDate: '2027-02-27',
    endDate: '2027-03-03',
    nights: 4,
    priceFrom: 1690000,
    tagline: '월드 메이저 6, 가장 가까운 도시에서.',
    highlights: ['참가권 보장', '왕복 항공편', '긴자/신주쿠 호텔', '한국인 가이드'],
    cover: img('runable-trip-tokyo'),
    badges: ['BEST', '월드 메이저'],
  },
  {
    id: 'rt-honolulu',
    slug: 'honolulu-marathon-2026',
    destination: '호놀룰루',
    country: '미국',
    raceName: '2026 호놀룰루 마라톤',
    startDate: '2026-12-12',
    endDate: '2026-12-17',
    nights: 5,
    priceFrom: 2890000,
    tagline: '다이아몬드 헤드 일출과 함께 달리는 26.2마일.',
    highlights: ['와이키키 비치 호텔', '트라이얼 러닝 투어', '참가권 보장'],
    cover: img('runable-trip-honolulu'),
    badges: ['선셋 코스'],
  },
  {
    id: 'rt-fuji',
    slug: 'fuji-yamanakako-half',
    destination: '후지산 산기슭',
    country: '일본',
    raceName: '후지 야마나카코 하프',
    startDate: '2026-09-19',
    endDate: '2026-09-22',
    nights: 3,
    priceFrom: 980000,
    tagline: '야마나카코 호수와 후지산을 한 화면에.',
    highlights: ['온천 료칸', '후지산 5합목 트레킹', '참가권 보장'],
    cover: img('runable-trip-fuji'),
    badges: ['트레일', '온천'],
  },
  {
    id: 'rt-florence',
    slug: 'florence-marathon-2026',
    destination: '피렌체',
    country: '이탈리아',
    raceName: '2026 피렌체 마라톤',
    startDate: '2026-11-27',
    endDate: '2026-12-02',
    nights: 5,
    priceFrom: 3290000,
    tagline: '두오모 광장을 출발선으로.',
    highlights: ['우피치 미술관 투어', '토스카나 와이너리', '참가권 보장'],
    cover: img('runable-trip-florence'),
  },
  {
    id: 'rt-budapest',
    slug: 'budapest-marathon-2026',
    destination: '부다페스트',
    country: '헝가리',
    raceName: '2026 부다페스트 마라톤',
    startDate: '2026-10-09',
    endDate: '2026-10-14',
    nights: 5,
    priceFrom: 2790000,
    tagline: '다뉴브 강을 따라 가을의 부다.',
    highlights: ['국회의사당 야경 투어', '세체니 온천', '참가권 보장'],
    cover: img('runable-trip-budapest'),
  },
  {
    id: 'rt-berlin',
    slug: 'berlin-marathon-2027',
    destination: '베를린',
    country: '독일',
    raceName: '2027 베를린 마라톤',
    startDate: '2027-09-24',
    endDate: '2027-09-29',
    nights: 5,
    priceFrom: 3490000,
    tagline: '세계기록의 코스, 가장 빠른 6.55%.',
    highlights: ['브란덴부르크 게이트 피니시', '참가권 보장', '프리미엄 호텔'],
    cover: img('runable-trip-berlin'),
    badges: ['월드 메이저'],
  },
];

export function priceLabel(price: number): string {
  return `${(price / 10000).toLocaleString()}만원~`;
}
